### ISSUE TITLE
[Notifications] Implement Server-Side API

### ISSUE THREAD

**Issue by hhuynhlam** [hhuynhlam/Hermes#31]
PUT /notifications = create a new notification
This could be multiple different routes for different types of notifications and req body. Or this could be one route, but we pass in req body to differentiate notification types.

POST /notifications { userId: int, type: varchar (optional) } = get notifications
This will get all notifications for a user. Optionally, we can pass in a type to filter one type for all notifications for a user.

DELETE /notifications/:id = delete all notifications for a single user

DELETE /notifications/:id/:type = delete all notifications for a single user, matching the type

**Comment by slybir** [comment]
New node route created with 2 new stored procedures.
